### ISSUE TITLE
Doesn't work with amazon-cognito-identity-js 

### ISSUE THREAD

**Issue by eox2** [grafana/k6-template-es6#2]
When i try to run the bundled version, it just hangs.

**Comment by eox2** [comment]
Looks like its not working because of cheerio. Well good, because I'm wondering how to solve this problem anyway. I want to use another library: https://www.npmjs.com/package/amazon-cognito-identity-js and this same thing happens, it hangs.

**Comment by simonaronsson** [comment]
Unfortunately, I don't think this will be possible, even though the `cheerio` issue has now been fixed (you can remove cheerio if you don't need it btw, it's just added as an example for how to use it). 

`amazon-cognito-identity-js` utilizes `fetch`, which k6 does not, and also expects promises and async operations to be available, which k6 lacks as well.

What you could do however, is to create an xk6 extension that solves this for you, using for instance https://docs.aws.amazon.com/sdk-for-go/api/service/cognitoidentity/, and then expose that API to your test script.

For details on how to get started with building an xk6 package, see https://k6.io/blog/extending-k6-with-xk6/

Best,
Simme
