### ISSUE TITLE
Webpack 4 vulnerabilities

### ISSUE THREAD

**Issue by hernanmateika-stuart** [grafana/k6-template-es6#23]
Hi! I have tried this using the node libs versions on your package.json and works fine. 
My concern is that this webpack version has some vulnerabilities, I have checked using Webpack 5  (latest version) but I'm getting this error when trying to execute the script :
`ERRO[0001] There were problems with the specified script configuration:
        - executor default: function 'default' not found in exports `

Anything that I can do to fix this? 
Thanks in advance!

**Comment by ppcano** [comment]
#24 has now upgraded to Webpack 5 and fixed the vulnerabilities. Thanks for taking the time to report this.
