### ISSUE TITLE
K6 hangs when I try to run this

### ISSUE THREAD

**Issue by DazKins** [grafana/k6-template-es6#3]
Not sure what I'm doing wrong. I've cloned this repo and followed the instructions:

```bash
npm i
npm run webpack
k6 run build/app.bundle.js
```

But it just hangs on this output:

```
$ k6 run build/app.bundle.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

```

Node version: `v14.16.0`

K6 version: `v0.31.1 ((devel), go1.16.2, darwin/amd64)`

**EDIT:** Note while it hangs in this state the CPU usage spikes really high: 
![image](https://user-images.githubusercontent.com/3652981/113151172-ba7e7c80-922c-11eb-8a2e-c306b2f7cffe.png)

**EDIT 2:** I left it running for about 10 minutes and it finally completed. Running at this CPU usage the whole time

**Comment by simonaronsson** [comment]
Hi!

Thank you for your report!

Did you do any changes to the project? For instance, add any node_modules, or alter the example in any way? 

Best,
Simme

**Comment by DazKins** [comment]
No, I kept it completely the same. I just ran the 3 commands I showed

**Comment by simonaronsson** [comment]
Seems to be related to cheerio in some way. xml2js works. I'll have a look and get back to you. 👍🏼

**Comment by simskij** [comment]
/remind me about getting back to @DazKins in 3 days

**Comment by simskij** [comment]
/remind me to check back on this on monday
